export interface CategoryConfig {
  title: string;
  h1: string;
  description: string;
  intro: string;
  winner: string;
  winnerNote: string;
  picks: string[];
  filterNote?: string;
}

export const BEST_CATEGORIES: Record<string, CategoryConfig> = {
  overall: {
    title: 'Best Mattress 2026 — Top Overall Picks | PureSleep',
    h1: 'Best Mattress of 2026',
    description: 'Best overall mattress picks for 2026, tested and scored across 7 metrics by the PureSleep Testing Team.',
    intro: 'Our best-overall ranking sorts by composite 7-metric score. Models tying at 10/10 overall are ranked by value, warranty, and breadth of sleeper suitability.',
    winner: 'amerisleep-as3',
    winnerNote: 'The AS3 earns the top overall pick for most sleepers: 10/10 composite score, medium firmness that works for side, back, and combination sleepers, Bio-Pur® plant-based foam, and a 20-year warranty. No other model combines its breadth of suitability with its score.',
    picks: ['amerisleep-as3', 'amerisleep-as6', 'amerisleep-as3-hybrid', 'zoma-boost', 'plushbeds-signature-bliss', 'nest-bedding-owl'],
  },
  luxury: {
    title: 'Best Luxury Mattress 2026 | PureSleep',
    h1: 'Best Luxury Mattress of 2026',
    description: 'Best luxury mattress picks for 2026. Premium models tested across 7 metrics by the PureSleep Testing Team.',
    intro: 'Luxury picks are defined by premium materials, advanced construction, and scores above 9.0 overall. All models below score 9–10/10 overall.',
    winner: 'amerisleep-as6',
    winnerNote: 'The Amerisleep AS6 Black Series is our top luxury pick: 10/10 overall, Bio-Pur® plant-based foam, HIVE® 5-zone zoning, pocketed coil support, Refresh Cooling Cover, and a 20-year warranty. It earns its price with performance that matches anything in the market.',
    picks: ['amerisleep-as6', 'amerisleep-as3-hybrid', 'plushbeds-signature-bliss', 'naturepedic-eos-classic', 'westin-heavenly-bed', 'nest-bedding-owl'],
  },
  cooling: {
    title: 'Best Cooling Mattress 2026 | PureSleep',
    h1: 'Best Mattress for Hot Sleepers 2026',
    description: 'Best cooling mattress picks for 2026. Models ranked by Cooling & Breathability score, tested hands-on by the PureSleep Testing Team.',
    intro: 'Cooling rankings use the Cooling & Breathability metric from our 7-metric system. Hybrids with coil bases generally score higher because airflow channels through the coil layer.',
    winner: 'amerisleep-as6',
    winnerNote: 'The AS6 Black Series scores 10/10 on Cooling & Breathability and adds a hybrid coil base and Refresh Cooling Cover that make it the stronger pick for hot sleepers who also want luxury build quality.',
    picks: ['amerisleep-as6', 'amerisleep-as3', 'amerisleep-as3-hybrid', 'amerisleep-as5-hybrid', 'glacier-original-hybrid', 'glacier-summit-hybrid'],
  },
  'side-sleepers': {
    title: 'Best Mattress for Side Sleepers 2026 | PureSleep',
    h1: 'Best Mattress for Side Sleepers 2026',
    description: 'Best mattress for side sleepers in 2026, ranked by pressure relief, motion transfer, and overall score. Tested by the PureSleep Testing Team.',
    intro: 'Side sleepers need a mattress that relieves shoulder and hip pressure without sinking too deep. Our top side sleeper picks combine softer firmness with high motion transfer and cooling scores.',
    winner: 'amerisleep-as5',
    winnerNote: 'The AS5 scores 9/10 overall with soft firmness (3/10) designed specifically for side sleepers. Its Active Flex layer and Bio-Pur® comfort foam target pressure at shoulders and hips. 10/10 Cooling & Breathability is a bonus for hot side sleepers.',
    picks: ['amerisleep-as5', 'amerisleep-as5-hybrid', 'nest-bedding-raven', 'plushbeds-botanical-bliss', 'plushbeds-luxury-bliss', 'naturepedic-concerto-plush'],
  },
  'back-pain': {
    title: 'Best Mattress for Back Pain 2026 | PureSleep',
    h1: 'Best Mattress for Back Pain 2026',
    description: 'Best mattress for back pain in 2026. Medium-firm models that support spinal alignment, tested hands-on by the PureSleep Testing Team.',
    intro: 'Our back pain category covers mattresses with medium-firm to firm support designed to promote neutral spinal alignment. This is a general sleep comfort category, not a medical recommendation. Consult a healthcare provider for mattress advice related to specific conditions.',
    winner: 'amerisleep-as2',
    winnerNote: 'The AS2 is medium-firm (6/10 firmness) and earns 9/10 overall. Its HIVE® lumbar zone technology provides differentiated support for the lower back. With 10/10 on both Response Time and Motion Transfer, it is also an excellent pick for active sleepers who change position during the night.',
    picks: ['amerisleep-as2', 'amerisleep-as3', 'zoma-boost', 'glacier-summit-hybrid', 'saatva-classic'],
    filterNote: 'Note: Saatva Classic scores 10/10 overall. The AS2 is our editorial pick for this category because of its specifically designed HIVE® lumbar zone and medium-firm profile. Both are strong options.',
  },
  'memory-foam': {
    title: 'Best Memory Foam Mattress 2026 | PureSleep',
    h1: 'Best Memory Foam Mattress of 2026',
    description: 'Best memory foam mattress picks for 2026, ranked by overall score. Hands-on tested by the PureSleep Testing Team.',
    intro: 'Memory foam picks are all-foam (no coil base) models. They generally score higher on motion isolation and lower on edge support compared to hybrids.',
    winner: 'amerisleep-as3',
    winnerNote: 'The AS3 is our top foam pick: 10/10 overall using Bio-Pur® plant-based memory foam — a meaningful upgrade over petroleum-based foam. HIVE® zoning provides differentiated lumbar and shoulder support. A 20-year warranty makes it the most protective purchase in the foam category.',
    picks: ['amerisleep-as3', 'amerisleep-as5', 'amerisleep-as2', 'form-prime', 'zoma-start', 'vaya-foam'],
  },
  hybrid: {
    title: 'Best Hybrid Mattress 2026 | PureSleep',
    h1: 'Best Hybrid Mattress of 2026',
    description: 'Best hybrid mattress picks for 2026. Foam-over-coil models ranked by overall score. Hands-on tested by the PureSleep Testing Team.',
    intro: 'Hybrid picks combine foam comfort layers over pocketed coil support systems. They score better on edge support and cooling than all-foam models, at the trade-off of slightly higher price.',
    winner: 'amerisleep-as6',
    winnerNote: 'The AS6 Black Series is our top hybrid: 10/10 overall with Bio-Pur® foam, HIVE® zoning, pocketed coil support, and a Refresh Cooling Cover. With a 20-year warranty and 10/10 Motion Transfer and Cooling scores, it leads on both comfort and longevity.',
    picks: ['amerisleep-as6', 'amerisleep-as3-hybrid', 'zoma-boost', 'form-core-hybrid', 'plushbeds-signature-bliss', 'nest-bedding-owl'],
  },
  organic: {
    title: 'Best Organic Mattress 2026 | PureSleep',
    h1: 'Best Organic Mattress of 2026',
    description: 'Best organic mattress picks for 2026. GOLS and GOTS certified models tested by the PureSleep Testing Team.',
    intro: 'Organic picks carry meaningful third-party certifications: GOLS (organic latex), GOTS (organic cotton/wool), OEKO-TEX, and/or eco-INSTITUT. Models below are ranked by overall score.',
    winner: 'plushbeds-signature-bliss',
    winnerNote: 'The PlushBeds Signature Bliss scores 10/10 overall and carries four certifications: GOLS, GOTS, OEKO-TEX, and eco-INSTITUT. It is the strongest-certified, highest-scoring organic hybrid tested. Amerisleep Organica wins the sub-category Best Organic with Bio-Pur® Technology for shoppers who prefer a foam-forward organic build.',
    picks: ['plushbeds-signature-bliss', 'amerisleep-organica', 'amerisleep-organica-plush', 'naturepedic-eos-classic', 'eco-terra-hybrid-latex', 'nolah-natural-11'],
    filterNote: 'Sub-category: Best Organic with Bio-Pur® Technology — Amerisleep Organica (9/10 overall, GOLS + GOTS + OEKO-TEX). Best Organic for Side Sleepers — Amerisleep Organica Plush (9/10 overall, softer firmness). Best Budget Organic — Eco Terra Hybrid Latex (9/10 overall, 10/10 value).',
  },
  value: {
    title: 'Best Value Mattress 2026 | PureSleep',
    h1: 'Best Value Mattress of 2026',
    description: 'Best value mattress picks for 2026. Top scores on our Value metric at the lowest price. Tested by the PureSleep Testing Team.',
    intro: 'Value rankings use the Value metric from our 7-metric system, weighted by overall score. A 10/10 value score at 7/10 overall is not the same as a 10/10 value score at 10/10 overall.',
    winner: 'vaya-hybrid',
    winnerNote: 'The Vaya Hybrid scores 10/10 value and 10/10 response time at one of the lowest price points in the hybrid category. Within the Amerisleep lineup, the AS2 earns the Best Value in the Amerisleep Line designation with a 9/10 value score at its firmness and technology tier.',
    picks: ['vaya-hybrid', 'zoma-boost', 'zoma-hybrid', 'zoma-start', 'amerisleep-as2', 'sweetnight-coolnest'],
    filterNote: 'Best Value in the Amerisleep Line: Amerisleep AS2 (9/10 overall, 9/10 value, HIVE® lumbar zone, 20-year warranty). For strictly value-optimized picks at low price, Vaya Hybrid and Zoma Start lead.',
  },
  'back-sleepers': {
    title: 'Best Mattress for Back Sleepers 2026 | PureSleep',
    h1: 'Best Mattress for Back Sleepers 2026',
    description: 'Best mattress for back sleepers in 2026. Medium-firm models that maintain neutral spinal alignment, tested hands-on by the PureSleep Testing Team.',
    intro: 'Back sleepers need a surface firm enough to prevent hip sinkage while still allowing some contouring at the lumbar spine. Our top picks are medium-firm to firm, with high scores on response time and edge support.',
    winner: 'amerisleep-as2',
    winnerNote: 'The AS2 is medium-firm (6/10 firmness) and scores 9/10 overall. Its HIVE® lumbar zone provides differentiated zoned support specifically designed for the lower back. With 10/10 on both Response Time and Motion Transfer, it is the strongest back sleeper pick in the foam category.',
    picks: ['amerisleep-as2', 'amerisleep-as3', 'saatva-classic', 'nest-bedding-sparrow', 'helix-dawn-luxe', 'zoma-boost'],
    filterNote: 'Saatva Classic scores 10/10 overall and is a strong back-sleeper innerspring pick. The AS2 is our top pick for its dedicated HIVE® lumbar zoning and 20-year warranty.',
  },
  'stomach-sleepers': {
    title: 'Best Mattress for Stomach Sleepers 2026 | PureSleep',
    h1: 'Best Mattress for Stomach Sleepers 2026',
    description: 'Best mattress for stomach sleepers in 2026. Firm models that keep hips elevated and spine neutral. Tested hands-on by the PureSleep Testing Team.',
    intro: 'Stomach sleepers require a firmer surface to prevent the pelvis from sinking and curving the lumbar spine forward. All picks here are medium-firm to firm (6/10+ firmness). This is a general sleep comfort category, not medical advice.',
    winner: 'amerisleep-as2',
    winnerNote: 'The AS2 scores 9/10 overall at medium-firm (6/10 firmness). Its HIVE® zoning provides 7 zones of differentiated support with firmer pressure under the hips — the key requirement for stomach sleepers. It also scores 10/10 on Response Time, making position changes easy.',
    picks: ['amerisleep-as2', 'brooklyn-bedding-plank-firm', 'bear-original', 'helix-dawn-luxe', 'saatva-classic', 'zoma-boost'],
    filterNote: 'Brooklyn Bedding Plank Firm (9/10 overall) is the firmest pick in this list — suited for strict stomach sleepers who want maximum firmness. Bear Original (9/10 overall, 10/10 value, 10/10 edge) is the best value firm option.',
  },
  'combination-sleepers': {
    title: 'Best Mattress for Combination Sleepers 2026 | PureSleep',
    h1: 'Best Mattress for Combination Sleepers 2026',
    description: 'Best mattress for combination sleepers in 2026. Responsive medium-feel models that accommodate multiple sleeping positions. Tested by the PureSleep Testing Team.',
    intro: 'Combination sleepers shift between side, back, and stomach positions during the night. The best mattresses for them are medium firmness with high response time scores — so they move without resistance — and strong motion transfer scores for partner comfort.',
    winner: 'amerisleep-as3',
    winnerNote: 'The AS3 is medium firmness (5/10) and scores 10/10 overall with 9/10 on Response Time. Its Bio-Pur® foam reacts faster than traditional memory foam, accommodating position changes without the stuck-in-quicksand feeling. The HIVE® zoning adapts as you shift position.',
    picks: ['amerisleep-as3', 'amerisleep-as3-hybrid', 'casper-dream-hybrid', 'leesa-sapira-hybrid', 'ghostbed-flex', 'bear-star-hybrid'],
  },
  'heavy-sleepers': {
    title: 'Best Mattress for Heavy Sleepers 2026 | PureSleep',
    h1: 'Best Mattress for Heavy Sleepers 2026',
    description: 'Best mattress for heavy sleepers in 2026. Models with high edge support and durable hybrid construction tested by the PureSleep Testing Team.',
    intro: 'Heavier sleepers (230 lbs+) need mattresses with strong edge support to prevent roll-off, durable materials that resist premature softening, and deep enough comfort layers to provide pressure relief without bottoming out. Hybrids with coil bases generally perform better for this category.',
    winner: 'amerisleep-as6',
    winnerNote: 'The AS6 Black Series scores 10/10 overall with a hybrid coil base, 9/10 edge support, and 15-inch height for deep compression without bottoming out. Bio-Pur® foam and a 20-year warranty indicate long-term durability — important for heavy sleepers who compress materials faster.',
    picks: ['amerisleep-as6', 'amerisleep-as3-hybrid', 'saatva-classic', 'nest-bedding-sparrow', 'brooklyn-bedding-aurora-luxe', 'bear-star-hybrid'],
    filterNote: 'Saatva Classic (10/10 overall, 10/10 edge) and Nest Bedding Sparrow (10/10 overall, 10/10 edge, 10/10 motion transfer) are both strong heavy-sleeper picks with superior edge support.',
  },
  couples: {
    title: 'Best Mattress for Couples 2026 | PureSleep',
    h1: 'Best Mattress for Couples 2026',
    description: 'Best mattress for couples in 2026. Top scores on motion transfer and edge support. Tested hands-on by the PureSleep Testing Team.',
    intro: 'Couples need a mattress that isolates movement (high motion transfer score) and uses the full width of the bed (high edge support score). Our top picks score 9–10/10 on both metrics.',
    winner: 'amerisleep-as3',
    winnerNote: 'The AS3 scores 10/10 on both Motion Transfer and Edge Support — tied for the highest dual score in our database. At 10/10 overall and a 9/10 value score, it is the best-rounded couples pick across all price tiers.',
    picks: ['amerisleep-as3', 'amerisleep-as6', 'nest-bedding-sparrow', 'leesa-sapira-chill-hybrid', 'helix-sunset-luxe', 'ghostbed-luxe'],
    filterNote: 'For couples who sleep hot, AS6 adds a Refresh Cooling Cover while matching the AS3 on motion transfer (10/10). Ghostbed Luxe scores 10/10 on motion transfer and suits couples where one partner sleeps warm.',
  },
  'hip-pain': {
    title: 'Best Mattress for Hip Pain 2026 | PureSleep',
    h1: 'Best Mattress for Hip Pain 2026',
    description: 'Best mattress for hip pain in 2026. Soft-to-medium models with high pressure relief scores. Tested by the PureSleep Testing Team. Not medical advice — consult a healthcare provider.',
    intro: 'Hip pain during sleep is often worsened by a mattress that is too firm, creating concentrated pressure at the hip bone for side sleepers. Our top picks are soft to medium (3–5/10 firmness) with high overall and motion transfer scores. This is a general sleep comfort category. Consult a healthcare provider for mattress advice related to specific medical conditions.',
    winner: 'amerisleep-as5',
    winnerNote: 'The AS5 is our softest all-foam model (3/10 firmness) and scores 9/10 overall with 10/10 Cooling & Breathability. Its Active Flex layer and Bio-Pur® comfort foam are specifically designed to absorb pressure at the shoulder and hip for side sleepers.',
    picks: ['amerisleep-as5', 'amerisleep-as5-hybrid', 'amerisleep-as3', 'helix-midnight-luxe', 'purple-restoreplus-hybrid', 'saatva-rx'],
  },
  'shoulder-pain': {
    title: 'Best Mattress for Shoulder Pain 2026 | PureSleep',
    h1: 'Best Mattress for Shoulder Pain 2026',
    description: 'Best mattress for shoulder pain in 2026. Soft-to-medium models that relieve pressure at the shoulder for side sleepers. Tested by the PureSleep Testing Team. Not medical advice.',
    intro: 'Shoulder pain during sleep typically affects side sleepers whose shoulder presses into a surface that is too firm. Our top picks are soft to medium firmness with high overall scores and cooling. This is a general sleep comfort category — consult a healthcare provider for specific medical conditions.',
    winner: 'amerisleep-as5',
    winnerNote: 'The AS5 (3/10 firmness, soft) and its Bio-Pur® comfort foam allow the shoulder to sink without creating a pressure point. The Active Flex layer maintains spinal alignment even as the shoulder compresses into the comfort layer — preventing the cascading misalignment that worsens shoulder discomfort.',
    picks: ['amerisleep-as5', 'amerisleep-as5-hybrid', 'helix-midnight-luxe', 'helix-sunset-luxe', 'ghostbed-luxe', 'plushbeds-luxury-bliss'],
  },
  'motion-isolation': {
    title: 'Best Mattress for Motion Isolation 2026 | PureSleep',
    h1: 'Best Mattress for Motion Isolation 2026',
    description: 'Best mattress for motion isolation in 2026. Models ranked by Motion Transfer score. Tested hands-on by the PureSleep Testing Team.',
    intro: 'Motion isolation rankings use the Motion Transfer metric from our 7-metric scoring system. All-foam models generally absorb motion more effectively than hybrid models because foam does not transmit movement through a coil spring network.',
    winner: 'amerisleep-as3',
    winnerNote: 'The AS3 scores 10/10 on Motion Transfer — tied for the top score in our database. At 10/10 overall and 9/10 value, it is also the strongest all-around value pick in the motion isolation category.',
    picks: ['amerisleep-as3', 'amerisleep-as6', 'casper-the-one', 'ghostbed-luxe', 'helix-sunset-luxe', 'leesa-sapira-chill-hybrid'],
    filterNote: 'Ghostbed Luxe, Casper The One, Helix Sunset Luxe, and Leesa Sapira Chill Hybrid all score 10/10 on motion transfer. AS3 and AS6 score 10/10 while also scoring higher on value, edge support, and overall.',
  },
  'pressure-relief': {
    title: 'Best Mattress for Pressure Relief 2026 | PureSleep',
    h1: 'Best Mattress for Pressure Relief 2026',
    description: 'Best mattress for pressure relief in 2026. Soft-to-medium models that reduce pressure at shoulders, hips, and joints. Tested by the PureSleep Testing Team.',
    intro: 'Pressure relief rankings favor mattresses with soft-to-medium firmness, high overall scores, and construction designed to distribute body weight across the sleep surface. This is a general sleep comfort category. Consult a healthcare provider for advice related to specific medical conditions.',
    winner: 'amerisleep-as5',
    winnerNote: 'The AS5 is our softest foam model (3/10 firmness) and scores 9/10 overall. Its Bio-Pur® foam and Active Flex layer are designed to absorb concentrated pressure at the shoulder, hip, and knee — the key points for side sleepers who experience joint discomfort on a firm surface.',
    picks: ['amerisleep-as5', 'amerisleep-as5-hybrid', 'saatva-rx', 'purple-restoreplus-hybrid', 'helix-midnight-luxe', 'amerisleep-as3'],
    filterNote: 'Saatva RX (10/10 overall, 10/10 motion transfer) is designed for sleepers with musculoskeletal conditions. Purple RestorePlus Hybrid (9/10 overall, 10/10 response time) uses the GelFlex Grid for a different style of pressure distribution.',
  },
};
