export const LEGACY_BEST_BLOG_REDIRECTS: Record<string, string> = {
  '/blog/best-mattress-for-back-sleepers/': '/best/back-sleepers/',
  '/blog/best-mattress-for-back-pain/': '/best/back-pain/',
  '/blog/best-mattress-for-side-sleepers/': '/best/side-sleepers/',
  '/blog/best-mattress-for-stomach-sleepers/': '/best/stomach-sleepers/',
  '/blog/best-mattress-for-combination-sleepers/': '/best/combination-sleepers/',
  '/blog/best-mattress-for-heavy-sleepers/': '/best/heavy-sleepers/',
  '/blog/best-mattress-for-petite-sleepers/': '/best/overall/',
  '/blog/best-mattress-for-couples/': '/best/couples/',
  '/blog/best-mattress-for-hot-sleepers/': '/best/cooling/',
  '/blog/best-organic-mattress/': '/best/organic/',
  '/blog/best-luxury-mattress/': '/best/luxury/',
  '/blog/best-mattress-for-hip-pain/': '/best/hip-pain/',
  '/blog/best-mattress-for-shoulder-pain/': '/best/shoulder-pain/',
  '/blog/best-mattress-for-sciatica/': '/best/back-pain/',
  '/blog/best-mattress-for-arthritis/': '/best/pressure-relief/',
  '/blog/best-mattress-for-fibromyalgia/': '/best/pressure-relief/',
  '/blog/best-mattress-for-lower-back-pain/': '/best/back-pain/',
  '/blog/best-mattress-for-seniors/': '/best/overall/',
  '/blog/best-mattress-for-pregnancy/': '/best/side-sleepers/',
  '/blog/best-mattress-for-athletes/': '/best/overall/',
  '/blog/best-mattress-for-upper-back-pain/': '/best/back-pain/',
  '/blog/best-mattress-under-1000/': '/best/value/',
  '/blog/best-memory-foam-mattress/': '/best/memory-foam/',
  '/blog/best-mattress-for-college-students/': '/best/value/',
  '/blog/best-mattress-for-guest-bedroom/': '/best/value/',
  '/blog/best-mattress-topper-for-back-pain/': '/guides/',
  '/blog/best-mattress-topper-for-pressure-relief/': '/guides/',
  '/blog/best-cooling-mattress-topper/': '/guides/',
  '/blog/best-pillow-for-side-sleepers/': '/guides/',
  '/blog/best-pillow-for-neck-pain/': '/guides/',
  '/blog/best-adjustable-bed-base/': '/guides/',
  '/blog/best-bamboo-sheets/': '/guides/',
  '/blog/best-mattress-protector/': '/guides/',
  '/blog/best-bed-frame-for-heavy-people/': '/guides/',
  '/blog/best-upholstered-bed-frame/': '/guides/',
  '/blog/best-mattress-for-back-pain-side-sleepers/': '/best/back-pain/',
  '/blog/best-sleep-position-for-back-pain/': '/topics/spinal-alignment/',
  '/blog/best-sleep-position-for-hip-pain/': '/topics/spinal-alignment/',
  '/blog/best-sleep-position-for-digestion/': '/guides/',
};

export const getLegacyBestBlogRedirect = (slug: string): string | undefined =>
  LEGACY_BEST_BLOG_REDIRECTS[`/blog/${slug}/`];
